services:
  beer-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - beer-db
    environment:
      - DATABASE_URL=mongodb://beer-db:27017
    networks:
      - beer-network

  beer-db:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - beer_data:/data/db
    networks:
      - beer-network

volumes:
  beer_data:

networks:
  beer-network:
    driver: bridge
